#!/usr/bin/bash
#retrieve the repo and install docker
DOCKER=`rpm -qa docker-ce`
if [[ $DOCKER == '' ]];then 
    yum install -y -q yum-utils
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    #[ edge != stable]
    #yum-config-manager --enable docker-ce-edge
    yum makecache
    yum install -y -q docker-ce
fi
